// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package customers

// Injectors from wire.go:

func InitializeCustomerController(customerService CustomerServiceProvider) *CustomerController {
	customerController := NewCustomerController(customerService)
	return customerController
}

func InitializeCustomerService() *CustomerService {
	customerService := NewCustomerService()
	return customerService
}
