// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package countries

// Injectors from wire.go:

func InitializeCountryController() *CountryController {
	countryController := NewCountryController()
	return countryController
}
